config/routes.rb
Examgoose::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'static_pages#index'
  get 'welcome' => 'static_pages#welcome'
  get 'thankyou' => 'static_pages#thankyou'
  get 'privacy' => 'static_pages#privacy'
  post 'interviews/claim' => 'interviews#claim'

  resources :users, :only => [:show, :update]

  resources :optins

  resources :interviews, :only => [:index, :show] do
    resources :charges, :only => [:new, :create]
  end

  namespace :admin do
    resources :interviews
    resources :questions
    resource :dashboard, :only => :show
    resource :users, :only => :show
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/interview.rb
class Interview < ActiveRecord::Base
	has_and_belongs_to_many :questions
	has_and_belongs_to_many :users

	validates :title, length: { in: 5..50 }, :presence => true, :uniqueness => true
	validates :description, length: { in: 20..300 }, :presence => true, :uniqueness => true

	def claimed?(user)
		self.users.include?(user)
	end

end

app/models/optin.rb
class Optin < ActiveRecord::Base

validates :name, presence: true
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }, :uniqueness => true, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :topic
	has_and_belongs_to_many :interviews
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :questions

	def self.collection_items
		Topic.all.collect do |topic|
			[topic.title, topic.id]
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :interviews

	def unclaimed_interview
		my_interviews = self.interviews
		all_interviews = Interview.all
		unclaimed_interviews = all_interviews - my_interviews
		unclaimed_interviews.shuffle.first
	end

	


end

app/controllers/admin/interviews_controller.rb
class Admin::InterviewsController < AdminController

  def index
    @interviews = Interview.all
  end

  def create
		@interview = Interview.new(interview_params)
   		if @interview.invalid?
      		flash[:alert] = 'Could not save the data you entered is invalid.'
      end
    
    @questions = Question.all
    @interview.save

		redirect_to admin_dashboard_path
	end

	private

	def  interview_params
		params.require(:interview).permit(:title, :description, :question_ids => [])
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate_user!
before_action :verify_admin


private

def verify_admin
	unless current_user && current_user.admin?
		flash[:alert] = "You are not authorized to access this page"
		#render :text => "You are not authorized to access this page", :status => :forbidden
		redirect_to root_path
	end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!


  def create

    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Exam Goose',
      :currency    => 'usd'
    )

    @current_interview ||= Interview.find(params[:interview_id])
    current_user.interviews << @current_interview
    redirect_to interviews_path, alert: "Thanks! You now have access to the selected interview."

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to interviews_path
  end


end


# In our create method, we’re creating a Stripe::Charge object with various POST parameters.
# Stripe expects charges to be in cents, so since we’re charging $5, we’ll need to set the amount parameter to 500.
# A Stripe Charge also takes an optional :description parameter, which in this case is Rails Stripe customer.
# Finally, we’re setting the :card property to the stripeToken parameter.
# This is something that is automatically created for us by Stripe’s Checkout, which we’re going to cover next.
# Some payments could fail, for a variety of reasons such as an invalid CVC, card number or failed charge.
# We can cater for this in a basic manner for the time being by catching any Stripe::CardError exceptions
#      and setting the flash hash.

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :unless_interview_claimed, :only => :show

  def index
    @interviews = Interview.all
  end


  def claim
    claimed_interview = current_user.unclaimed_interview
    if current_user.interviews.count != 0
      redirect_to interviews_path,  :alert => 'You already claimed a free interview'
    else
     current_user.interviews << claimed_interview
     redirect_to interview_path(claimed_interview)
    end
  end


  def show
  #  @interviews = current_user.interviews (a current user's interviews can be
  #  viewed on the index page or moved to the user's dashboard)
  @interviews = current_interview.questions
  end

  private

  helper_method :current_interview

  def current_interview
    @current_interview ||= Interview.find(params[:id])
  end

  def unless_interview_claimed
    unless current_interview.claimed? current_user
      render :text => "You must claim this interview before viewing it.",
      :status => :forbidden
    end
  end

end

app/controllers/optins_controller.rb
class OptinsController < ApplicationController

	def new
		@optin = Optin.new
	end

	def create
		 #render plain: params[:optin].inspect
		@optin = Optin.create(optin_params)

		 #if @optin.valid?
			redirect_to thankyou_path
		 #else
		 #render :new, :status => :unprocessable_entity
		 #end
	end

	private

	def optin_params
		params.require(:optin).permit(:name,:email)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, :only => :welcome

  def index
    if current_user.present? && current_user.admin?
      redirect_to admin_dashboard_path
    elsif newuser
      redirect_to welcome_path
    elsif current_user
      redirect_to interviews_path
    end
  end

  def welcome
    @unclaimed = current_user.unclaimed_interview
  end

  def thankyou
    if current_user.present?
    redirect_to welcome_path
    end
  end

  def privacy
  end

  private

  def newuser
    current_user && current_user.interviews.count == 0
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	def show			#add show action, as called in routes
		@user = User.find(params[:id])
    @user_email = current_user.email
    @users = User.all
	end

	def index
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(:firehose => params[:firehose])
			flash[:alert] = "Firehoser given all interviews!"
			@user.interviews << Interview.all
			redirect_to admin_dashboard_path

		else
			flash[:alert] = "Didn't work"
			redirect_to admin_dashboard_path
		end
	end








end

app/helpers/admin/interviews_helper.rb
module Admin::InterviewsHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/optins_helper.rb
module OptinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/interviews/index.html.erb
<h1>Welcome, admin</h1>

app/views/interviews/index.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Interviews</h1>
  <hr />

  <% @interviews.each do |interview| %>
  <div class="panel panel-info">
    <div class="panel-heading"><h3 class="panel-title"><%= interview.title %></h2></div>
    <div class="panel-body">
      <%= interview.description %>
      <% if current_user && interview.claimed?(current_user) %>
      <%= link_to 'View Interview', interview_path(interview), :class => 'btn btn-primary pull-right' %>
      <% else %>
        <span class="label label-success pricing pull-right">
        $5.00
        </span>
        <br />
        <br />
        <%= form_tag interview_charges_path(interview), method: 'POST', class: 'pull-right' %>
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key='<%= Rails.configuration.stripe[:publishable_key] %>'
            data-description="Purchase a new interview item."
            data-amount="500"
            data-name="Exam Goose"
            data-image="/assets/exam.png">
          </script>
        </form>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/interviews/show.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel">Questions and Answers</h4>
			</div>
			<div class="modal-body">
						<% @interviews.each do |question| %>
							<div class="quiz-box col-xs-10 col-xs-offset-1">
									<div class="set">
										<p><strong> Q: <%= question.problem %></strong></p>
									</div>
									<div class="set">
										<p> A: <%= question.solution %></p>
									</div>
							</div>
						<% end %>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<div class="quiz-box col-xs-10 col-xs-offset-1">
<h2><strong><%= current_interview.title %></strong></h2>
<p><%= current_interview.description %></p>
</div>
<br><br><br>

<div class="interviewbox">
<% @interviews.each do |question| %>
	<div class="set col-xs-10 col-xs-offset-1">
				<p><%= question.problem %></p>
	</div>
<% end %><br><br>
</div>

<div class="button col-xs-2 col-xs-offset-5">
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg text-center" data-toggle="modal" data-target="#myModal">
	Show the answers
</button>
</div>