config/routes.rb
Examgoose::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'static_pages#index'
  get 'welcome' => 'static_pages#welcome'
  get 'thankyou' => 'static_pages#thankyou'
  get 'privacy' => 'static_pages#privacy'
  post 'interviews/claim' => 'interviews#claim'

  resources :users, :only => [:show, :update]

  resources :optins

  resources :interviews, :only => [:index, :show] do
    resources :charges, :only => [:new, :create]
  end

  namespace :admin do
    resources :interviews
    resources :questions
    resource :dashboard, :only => :show
    resource :users, :only => :show
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/interview.rb
class Interview < ActiveRecord::Base
	has_and_belongs_to_many :questions
	has_and_belongs_to_many :users

	validates :title, length: { in: 5..50 }, :presence => true, :uniqueness => true
	validates :description, length: { in: 20..300 }, :presence => true, :uniqueness => true

	def claimed?(user)
		self.users.include?(user)
	end

end

app/models/optin.rb
class Optin < ActiveRecord::Base

validates :name, presence: true
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }, :uniqueness => true, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :topic
	has_and_belongs_to_many :interviews
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :questions

	def self.collection_items
		Topic.all.collect do |topic|
			[topic.title, topic.id]
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :interviews

	def unclaimed_interview
		my_interviews = self.interviews
		all_interviews = Interview.all
		unclaimed_interviews = all_interviews - my_interviews
		unclaimed_interviews.shuffle.first
	end

	


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate_user!
before_action :verify_admin


private

def verify_admin
	unless current_user && current_user.admin?
		flash[:alert] = "You are not authorized to access this page"
		#render :text => "You are not authorized to access this page", :status => :forbidden
		redirect_to root_path
	end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!


  def create

    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Exam Goose',
      :currency    => 'usd'
    )

    @current_interview ||= Interview.find(params[:interview_id])
    current_user.interviews << @current_interview
    redirect_to interviews_path, alert: "Thanks! You now have access to the selected interview."

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to interviews_path
  end


end


# In our create method, we’re creating a Stripe::Charge object with various POST parameters.
# Stripe expects charges to be in cents, so since we’re charging $5, we’ll need to set the amount parameter to 500.
# A Stripe Charge also takes an optional :description parameter, which in this case is Rails Stripe customer.
# Finally, we’re setting the :card property to the stripeToken parameter.
# This is something that is automatically created for us by Stripe’s Checkout, which we’re going to cover next.
# Some payments could fail, for a variety of reasons such as an invalid CVC, card number or failed charge.
# We can cater for this in a basic manner for the time being by catching any Stripe::CardError exceptions
#      and setting the flash hash.

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :unless_interview_claimed, :only => :show

  def index
    @interviews = Interview.all
  end


  def claim
    claimed_interview = current_user.unclaimed_interview
    if current_user.interviews.count != 0
      redirect_to interviews_path,  :alert => 'You already claimed a free interview'
    else
     current_user.interviews << claimed_interview
     redirect_to interview_path(claimed_interview)
    end
  end


  def show
  #  @interviews = current_user.interviews (a current user's interviews can be
  #  viewed on the index page or moved to the user's dashboard)
  @interviews = current_interview.questions
  end

  private

  helper_method :current_interview

  def current_interview
    @current_interview ||= Interview.find(params[:id])
  end

  def unless_interview_claimed
    unless current_interview.claimed? current_user
      render :text => "You must claim this interview before viewing it.",
      :status => :forbidden
    end
  end

end

app/controllers/optins_controller.rb
class OptinsController < ApplicationController

	def new
		@optin = Optin.new
	end

	def create
		 #render plain: params[:optin].inspect
		@optin = Optin.create(optin_params)

		 #if @optin.valid?
			redirect_to thankyou_path
		 #else
		 #render :new, :status => :unprocessable_entity
		 #end
	end

	private

	def optin_params
		params.require(:optin).permit(:name,:email)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, :only => :welcome

  def index
    if current_user.present? && current_user.admin?
      redirect_to admin_dashboard_path
    elsif newuser
      redirect_to welcome_path
    elsif current_user
      redirect_to interviews_path
    end
  end

  def welcome
    @unclaimed = current_user.unclaimed_interview
  end

  def thankyou
    if current_user.present?
    redirect_to welcome_path
    end
  end

  def privacy
  end

  private

  def newuser
    current_user && current_user.interviews.count == 0
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	def show			#add show action, as called in routes
		@user = User.find(params[:id])
    @user_email = current_user.email
    @users = User.all
	end

	def index
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(:firehose => params[:firehose])
			flash[:alert] = "Firehoser given all interviews!"
			@user.interviews << Interview.all
			redirect_to admin_dashboard_path

		else
			flash[:alert] = "Didn't work"
			redirect_to admin_dashboard_path
		end
	end








end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/optins_helper.rb
module OptinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<!-- success on charge message -->
<h2>Thanks, you paid <strong>$5.00</strong> for one new course!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <div class="col-xs-2 col-xs-offset-5 charge-box text-center">
      <article>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key='<%= Rails.configuration.stripe[:publishable_key] %>'
            data-description="Sign up for one new course."
            data-amount="500"></script>
  </div>
<% end %>

app/views/static_pages/admin.html.erb
<br/>

<div class="container">
    <div id="content">
        <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
            <li class="active"><a href="#dashboard" data-toggle="tab">Dashboard</a></li>
            <li><a href="#questions" data-toggle="tab">Questions</a></li>
            <li><a href="#interviews" data-toggle="tab">Interviews</a></li>
            <li><a href="#users" data-toggle="tab">Users</a></li>
        </ul>

        <div id="my-tab-content" class="tab-content">
            <div class="tab-pane active" id="dashboard">
                <h1>Dashboard</h1>
                
            </div>
            <div class="tab-pane" id="questions">
                <br/>
                <div class="panel panel-default span8">
                    <div class="panel-heading">Panel heading</div>
                    <table class="table">
                        <thead>
                            <tr>
                                <td>Topic</td>
                                <td>Question</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                        
                    </table>
                </div>    
            </div>

            <div class="tab-pane" id="interviews">
                <h1>Interviews</h1>
                
            </div>
            <div class="tab-pane" id="users">
                <h1>Users</h1>
                
            </div>
        </div>
    </div>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
<h1 class="text-center">Crush Your Next <strong>Technical Interview</strong></h1>
<h2 class="text-center">by getting the skills to snag that dream job you've always wanted...</h2>
</div>
<section class="text-center about">
<h3 class="col-xs-8 col-xs-offset-2">Much of the process of landing a job as a junior web developer is getting prepared to face the technical interview.  <strong>Exam Goose prepares you to crush it and get that job offer.</strong></h3>
<br class="clr"/>
</section>
<%= image_tag 'divider-gray.png', :class => 'img-responsive' %>

<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="col-sm-4">
    <h3>Test your knowledge</h3>
    <p>Get ready for your technical interview with curated questions for the subject of your choosing.</p> <br />
  </div>

  <div class="col-sm-4">
    <h3>Real interview problems</h3>
    <p>Interview questions that commonly show up in your selected interview type, and  how to nail them.</p><br />
  </div>

  <div class="col-sm-4">
    <h3>Your First Set Free</h3>
    <p>The first set of questions are free, and you have the option to unlock more for just $5.</p>
  </div>

</div>

<br class="clr" />

<div class="sign-up col-xs-10 col-xs-offset-1 text-center">
	<h2>Get started</h2>
  <p>
    Enter your name and your email address so we'll be able to notify you when Exam Goose is live.
  </p>

  <%= simple_form_for Optin.new do |f| %>
    <div class="simple_form form-inline">
      <div class="form-group">
        <%= f.input :name, placeholder: 'Name', label: false %>
      </div>

      <div class="form-group">
        <%= f.input :email, :placeholder => 'Email', label: false %>
      </div>
      <br />
      <br />
      <%= f.submit 'Get notified', :class => 'btn btn-success btn-sm' %>
    </div>
  <% end %>
</div>


<br class="clr"/>

app/views/static_pages/privacy.html.erb
<h1 class="text-center">Our Privacy Policy</h1>

<body>
<div class="col-xs-10 col-xs-offset-1">
	<h3>The standard Lorem Ipsum passage, used since the 1500s</h3>
<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
<h3>Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</h3>
<p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
<h3>1914 translation by H. Rackham</h3>
<p>"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"</p>
<h3>Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</h3>
<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
<h3>1914 translation by H. Rackham</h3>
<p>"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."</p>
</div>

app/views/static_pages/thankyou.html.erb
<br />
<br />
<br />

<div class="sign-up col-xs-10 col-xs-offset-1 text-center">
<%= image_tag 'emailplane.png', :id => 'thanksimg' %>
<h2>Thanks for giving us your e-mail!</h2>
<p>We'll let you know as soon as we're live so you can CRUSH that interview!</p>
</div>

app/views/static_pages/welcome.html.erb
<div class="head col-xs-12 text-center">
<h1>How to use this Resource:</h1>
</div>


<div class="course-head col-xs-8 col-xs-offset-2 text-center">
<h2>What is a technical interview?</h2><br>
<h2>How do they work?</h2><br>
<h2>How to prepare.</h2>
</div>
<br><br><br><br>
<div class="courses col-xs-4 col-xs-offset-4 text-center">
  <% if @unclaimed.nil? %>
	<h4><%= "Sorry, no more interviews.  You got 'em all!" %></h4>
  <% else %>
    <h3><%= link_to "Give me one for free", interviews_claim_path, :method => :post %></h3>
  <% end %>
</div>