config/routes.rb
Examgoose::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'static_pages#index'
  get 'welcome' => 'static_pages#welcome'
  get 'thankyou' => 'static_pages#thankyou'
  get 'privacy' => 'static_pages#privacy'
  post 'interviews/claim' => 'interviews#claim'

  resources :users, :only => [:show, :update]

  resources :optins

  resources :interviews, :only => [:index, :show] do
    resources :charges, :only => [:new, :create]
  end

  namespace :admin do
    resources :interviews
    resources :questions
    resource :dashboard, :only => :show
    resource :users, :only => :show
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/interview.rb
class Interview < ActiveRecord::Base
	has_and_belongs_to_many :questions
	has_and_belongs_to_many :users

	validates :title, length: { in: 5..50 }, :presence => true, :uniqueness => true
	validates :description, length: { in: 20..300 }, :presence => true, :uniqueness => true

	def claimed?(user)
		self.users.include?(user)
	end

end

app/models/optin.rb
class Optin < ActiveRecord::Base

validates :name, presence: true
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }, :uniqueness => true, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :topic
	has_and_belongs_to_many :interviews
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :questions

	def self.collection_items
		Topic.all.collect do |topic|
			[topic.title, topic.id]
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :interviews

	def unclaimed_interview
		my_interviews = self.interviews
		all_interviews = Interview.all
		unclaimed_interviews = all_interviews - my_interviews
		unclaimed_interviews.shuffle.first
	end

	


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate_user!
before_action :verify_admin


private

def verify_admin
	unless current_user && current_user.admin?
		flash[:alert] = "You are not authorized to access this page"
		#render :text => "You are not authorized to access this page", :status => :forbidden
		redirect_to root_path
	end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!


  def create

    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Exam Goose',
      :currency    => 'usd'
    )

    @current_interview ||= Interview.find(params[:interview_id])
    current_user.interviews << @current_interview
    redirect_to interviews_path, alert: "Thanks! You now have access to the selected interview."

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to interviews_path
  end


end


# In our create method, we’re creating a Stripe::Charge object with various POST parameters.
# Stripe expects charges to be in cents, so since we’re charging $5, we’ll need to set the amount parameter to 500.
# A Stripe Charge also takes an optional :description parameter, which in this case is Rails Stripe customer.
# Finally, we’re setting the :card property to the stripeToken parameter.
# This is something that is automatically created for us by Stripe’s Checkout, which we’re going to cover next.
# Some payments could fail, for a variety of reasons such as an invalid CVC, card number or failed charge.
# We can cater for this in a basic manner for the time being by catching any Stripe::CardError exceptions
#      and setting the flash hash.

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :unless_interview_claimed, :only => :show

  def index
    @interviews = Interview.all
  end


  def claim
    claimed_interview = current_user.unclaimed_interview
    if current_user.interviews.count != 0
      redirect_to interviews_path,  :alert => 'You already claimed a free interview'
    else
     current_user.interviews << claimed_interview
     redirect_to interview_path(claimed_interview)
    end
  end


  def show
  #  @interviews = current_user.interviews (a current user's interviews can be
  #  viewed on the index page or moved to the user's dashboard)
  @interviews = current_interview.questions
  end

  private

  helper_method :current_interview

  def current_interview
    @current_interview ||= Interview.find(params[:id])
  end

  def unless_interview_claimed
    unless current_interview.claimed? current_user
      render :text => "You must claim this interview before viewing it.",
      :status => :forbidden
    end
  end

end

app/controllers/optins_controller.rb
class OptinsController < ApplicationController

	def new
		@optin = Optin.new
	end

	def create
		 #render plain: params[:optin].inspect
		@optin = Optin.create(optin_params)

		 #if @optin.valid?
			redirect_to thankyou_path
		 #else
		 #render :new, :status => :unprocessable_entity
		 #end
	end

	private

	def optin_params
		params.require(:optin).permit(:name,:email)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, :only => :welcome

  def index
    if current_user.present? && current_user.admin?
      redirect_to admin_dashboard_path
    elsif newuser
      redirect_to welcome_path
    elsif current_user
      redirect_to interviews_path
    end
  end

  def welcome
    @unclaimed = current_user.unclaimed_interview
  end

  def thankyou
    if current_user.present?
    redirect_to welcome_path
    end
  end

  def privacy
  end

  private

  def newuser
    current_user && current_user.interviews.count == 0
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	def show			#add show action, as called in routes
		@user = User.find(params[:id])
    @user_email = current_user.email
    @users = User.all
	end

	def index
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(:firehose => params[:firehose])
			flash[:alert] = "Firehoser given all interviews!"
			@user.interviews << Interview.all
			redirect_to admin_dashboard_path

		else
			flash[:alert] = "Didn't work"
			redirect_to admin_dashboard_path
		end
	end








end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/optins_helper.rb
module OptinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/_footer.html.erb
<br style="clear:both" />

<div id="footer">
  <div class="container">
    <div class="col-xs-6 col-sm-3">
      <b>Teachers</b>
      <br />
      <a href="#">Something</a>
      <br />
      <a href="#">Something Else</a>
    </div>
    <div class="col-xs-6 col-sm-3">
      <b>About</b>
      <br />
      <a href="#">Team</a>
      <br />
      <a href="#">Careers</a>
      <br />
      <%= link_to 'Privacy Policy', privacy_path %>
    </div>
    <div class="col-xs-6 col-sm-3">
      <b>Contact</b>
      <br />
      team@examgoose.com
      <br />
      Boston &amp; Germany
      <br />
      Built as part of theFirehoseProject
    </div>
    <div class="col-xs-6 col-sm-3 social">
      <b>Social</b>
      <br />
      <br />
      <%= image_tag 'github.png' %>  
      <%= image_tag 'facebook.png' %>
      <%= image_tag 'twitter.png' %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'Exam Goose', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Welcome, #{current_user.email}", user_path(current_user) %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Admin Area", admin_dashboard_path %></li>
          <% end %>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_new_interview.html.erb
<!-- Modal -->
<div class="modal fade" id="interviewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new interview</h4>
      </div>
      <div class="modal-body row">
        <%= simple_form_for @interview, :url => admin_interviews_path do |f| %>
        <%= f.input :title %>
        <%= f.input :description, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Mini'} } %>
        <% @topics.each do |topic| %>
            <%= f.association :questions, :collection => topic.questions, as: :select, :label_method => :problem, :value_method => :id, :label => "Select question for #{topic.title}: ", :include_blank => false%>
            <% end %>
	   </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= f.submit 'Add', :class => 'btn btn-danger' %>
	         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_new_question.html.erb
<!-- Modal -->
<div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new question</h4>
      </div>
      <div class="modal-body row">
        <%= simple_form_for @question, :url => admin_questions_path do |f| %>
        <div class="col-sm-2">Topic</div>
        <div class="col-sm-10"><%= f.input_field :topic_id, :label => "Topic id", :placeholder => "bla", :as => :select, :collection => Topic.collection_items %></div><br>

        <div class="col-sm-2">Question</div>
        <div class="col-sm-10"><%= f.input :problem, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Mini'} } %></div>

        <div class="col-sm-2">Answer</div>
        <div class="col-sm-10"><%= f.input :solution, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Mini'} } %></div>
	   </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= f.submit 'Add', :class => 'btn btn-danger' %>
	  <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Examgoose</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>


<body class="Site">
  <main class="Site-content">
	<div id="container">
		<%= render :partial => "layouts/header" %>


		<% if notice.present? %>
      <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= notice %>
    </div>
		  <!-- <p class="alert alert-info"><%= notice %></p> -->
		<% end %>
		<% if alert.present? %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= alert %>
    </div>
      <!-- <%= alert_box alert, dismissible: true %>
		  <p class="alert alert-danger"><%= alert %></p> -->
		<% end %>
  </div>
	</div>


	<%= yield %>

</main>


<%= render :partial => 'layouts/footer' %>

</body>
</html>